<?php
// Generated by install.sh — local overrides for config/app.php
// Copy to app.local.php and edit. Never commit app.local.php.
return [
    'db' => [
        'host' => '127.0.0.1',
        'port' => '5432',
        'name' => 'atr',
        'user' => 'atr',
        'pass' => 'CHANGE_ME',
    ],
    'mail' => [
        'from' => 'atr-inventory@localhost',
        'smtp_host' => '',
        'smtp_port' => 587,
        'smtp_user' => '',
        'smtp_pass' => '',
    ],
];
